# Решение
## Клиент
Клиент получает на имя функции и её аргументы и конструирует сообщение, добавляя в заголовок уникальный `ID` . Тип сообщения -- имя функции, которую надо вызвать, а в теле содержатся аргументы функций. 

После этого сообщение отправляется серверу, и ожидается ответ с таймаутом 1. 

Если ответ пришёл и его `ID` совпадает с `ID` отправленного сообщения, то мы смотрим на его тип. Если это `ERROR`, то значит при исполнении команды на сервере выпало исключение. Тогда клиент бросает исключение с тем же сообщением об ошибке. Если тип сообщение -- это `RESULT`, то мы десериализуем тело сообщения, получаем результат исполнения команды и возвращаем его.

Если сообщение не пришло или у него оказался другой `ID`, то если операция идемпотентна (`get`, `put` и `remove`), то то же сообщение перепосылается заново и происходит то же самое. Если нет, то бросается исключение. 

## Сервер
Сервер кэширует `ID` приходящих ему запросов и ответ, которое он на этот запрос уже отправил. В бесконечном цикле получает сообщения, если такое сообщение уже было, то он берёт ответ из кэша. Если нет, то при помощи `gettatr` вызывает нужный метод у хранилища, предварительно десериализовав аргументы. Если при исполнении команды выпало исключение, посылает сообщение типа `ERROR` с текстом ошибки в теле сообщения. Если команда удачно завершила, отправляет сериализованный результат. 

## Тесты
Добавлен один тест, который проверяет, что `remove` отправляется заново, если в первый раз ответ не был получен (то есть считается идемпотентной) и тест, который проверяет гарантию at most once для `append`.